services:
  unflare:
    build: .
    image: unflare
    container_name: unflare
    ports:
      - "5002:5002"

  bypass-cloudflare-proxy:
    build:
      context: .
      dockerfile: Dockerfile.addon
    container_name: bypass-cloudflare-proxy
    command: node script.js
    ports:
      - "5003:5003"
    environment:
      - UNFLARE_URL=${UNFLARE_URL:-http://unflare:5002}
      - ADDON_PORT=${ADDON_PORT:-5003}
      - DOMAIN_WHITELIST=${DOMAIN_WHITELIST:-} # Optional: Comma-separated list of allowed domains (e.g., example.com,test.com)
    depends_on:
      - unflare
    volumes:
      - ./script.js:/usr/src/app/script.js